"use client";
import { motion, useReducedMotion } from 'framer-motion';

const experience = [
  { role: 'Application Developer Intern · Full Stack Development', company: 'Eide Bailly LLP', date: 'Jan 2024 — Aug 2024', location: 'Fargo, ND', description: 'Engineered a secure full-stack hardware lifecycle and fulfillment application with Angular, TypeScript, Kendo UI, C#/.NET, REST APIs, JWT, and SQL Server. It automated employee hardware selection and IT fulfillment workflows, improving process efficiency by 40%. Designed a CI/CD pipeline with Git, GitHub, and Microsoft Azure to make releases repeatable. Also migrated four legacy applications from .NET Framework 4 and .NET 6 to .NET 8, preserving internal functionality and improving performance by approximately 25%.' },
  { role: 'Application Developer Co-op', company: 'Doosan Digital Innovation America, LLC', date: 'May 2023 — Dec 2023', location: 'West Fargo, ND', description: 'Enhanced production reporting applications with Angular, TypeScript, C#/.NET, and Oracle SQL, including a work-in-progress reporting screen spanning frontend components, backend logic, and database queries. Diagnosed manufacturing-data issues in Apriso MES by tracing Oracle SQL logic, reducing troubleshooting time by approximately 25%. Improved work-order and production-order workflows and served as Deployment Manager across seven factory sites, coordinating releases from pre-production to production in an Agile environment.' },
  { role: 'Project Manager', company: 'Computer Science Society, Concordia College', date: 'May 2023 — May 2024', location: 'Moorhead, MN', link: 'https://www.concordiacollege.edu/', description: 'Directed planning and development of the club website, using GitHub and Jira to organize the software development lifecycle. Collaborated with student leaders and faculty advisors to revitalize and relaunch the Computer Science Club.' },
  { role: 'Student Manager', company: 'IT Solution Center, Concordia College', date: 'Jan 2023 — Dec 2023', location: 'Moorhead, MN', link: 'https://www.concordiacollege.edu/', description: 'Managed a team of 14 student employees, providing guidance, training, and support for daily operations. Helped enforce IT policies and procedures while fostering a safe and productive environment.' },
  { role: 'Student Technician', company: 'IT Solution Center, Concordia College', date: 'May 2022 — Dec 2022', location: 'Moorhead, MN', link: 'https://www.concordiacollege.edu/', description: 'Troubleshot software and hardware issues, performed installations and minor repairs, and provided online and phone support to customers.' },
  { role: 'Study Away Office Assistant', company: 'Concordia College', date: 'Sept 2021 — May 2022', location: 'Moorhead, MN', link: 'https://www.concordiacollege.edu/', description: 'Advised students interested in Study Away programs, supported paperwork, and answered questions by phone, email, and in person. Managed multiple projects using organizational and analytical skills.' },
  { role: 'Bachelor of Arts in Computer Science', company: 'Concordia College', date: 'Graduated Spring 2024', location: 'Moorhead, MN', link: 'https://www.concordiacollege.edu/', description: 'Studied data structures and algorithms, web and mobile application development, operating systems, databases, computer networks, and software engineering. Activities included the Computer Science Society and ColorStack.' },
];

export default function Experience() {
  const reduceMotion = useReducedMotion();
  const pop = { initial: { y: reduceMotion ? 0 : 52, scale: reduceMotion ? 1 : .99 }, whileInView: { y: 0, scale: 1 }, viewport: { once: true, amount: .18 }, transition: { type: 'spring', stiffness: 260, damping: 13 } };
  return <section id="experience" className="section" aria-labelledby="experience-title">
    <div className="section-heading"><div><span className="eyebrow section-kicker">03 / ALONG THE WAY</span><h2 id="experience-title">Experience that shapes my work<span className="accent">.</span></h2></div></div>
    <ol className="experience-list">{experience.map(item => <motion.li className="experience-row" key={item.role} {...pop}><div className="experience-date">{item.date}<span>{item.location}</span></div><div><h3>{item.role}</h3>{item.link ? <a className="experience-company" href={item.link} target="_blank" rel="noreferrer">{item.company} ↗</a> : <span className="experience-company">{item.company}</span>}<p>{item.description}</p></div></motion.li>)}</ol>
  </section>;
}
